### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by qkqpttgf** [alvarcarto/url-to-pdf-api#165]
2021-06-02T02:19:23.095288+00:00 app[web.1]: 2021-06-02T02:19:23.095Z - info: [render-core.js] Rendering with opts: {
2021-06-02T02:19:23.095307+00:00 app[web.1]:   "cookies": [],
2021-06-02T02:19:23.095307+00:00 app[web.1]:   "scrollPage": false,
2021-06-02T02:19:23.095308+00:00 app[web.1]:   "emulateScreenMedia": true,
2021-06-02T02:19:23.095308+00:00 app[web.1]:   "ignoreHttpsErrors": false,
2021-06-02T02:19:23.095309+00:00 app[web.1]:   "html": null,
2021-06-02T02:19:23.095309+00:00 app[web.1]:   "viewport": {
2021-06-02T02:19:23.095310+00:00 app[web.1]:     "width": 1600,
2021-06-02T02:19:23.095310+00:00 app[web.1]:     "height": 1200
2021-06-02T02:19:23.095311+00:00 app[web.1]:   },
2021-06-02T02:19:23.095311+00:00 app[web.1]:   "goto": {
2021-06-02T02:19:23.095312+00:00 app[web.1]:     "waitUntil": "networkidle0"
2021-06-02T02:19:23.095312+00:00 app[web.1]:   },
2021-06-02T02:19:23.095312+00:00 app[web.1]:   "output": "screenshot",
2021-06-02T02:19:23.095313+00:00 app[web.1]:   "pdf": {
2021-06-02T02:19:23.095313+00:00 app[web.1]:     "format": "A4",
2021-06-02T02:19:23.095313+00:00 app[web.1]:     "printBackground": true,
2021-06-02T02:19:23.095314+00:00 app[web.1]:     "margin": {}
2021-06-02T02:19:23.095314+00:00 app[web.1]:   },
2021-06-02T02:19:23.095314+00:00 app[web.1]:   "screenshot": {
2021-06-02T02:19:23.095315+00:00 app[web.1]:     "type": "png",
2021-06-02T02:19:23.095315+00:00 app[web.1]:     "fullPage": true,
2021-06-02T02:19:23.095316+00:00 app[web.1]:     "clip": {}
2021-06-02T02:19:23.095316+00:00 app[web.1]:   },
2021-06-02T02:19:23.095316+00:00 app[web.1]:   "failEarly": false,
2021-06-02T02:19:23.095318+00:00 app[web.1]:   "url": "https://herooneindex.herokuapp.com/E5/"
2021-06-02T02:19:23.095318+00:00 app[web.1]: }
2021-06-02T02:19:23.335080+00:00 app[web.1]: 2021-06-02T02:19:23.334Z - info: [render-core.js] Set browser viewport..
2021-06-02T02:19:23.337539+00:00 app[web.1]: 2021-06-02T02:19:23.337Z - info: [render-core.js] Emulate @media screen..
2021-06-02T02:19:23.338562+00:00 app[web.1]: 2021-06-02T02:19:23.338Z - info: [render-core.js] Goto url https://herooneindex.herokuapp.com/E5/ ..
2021-06-02T02:19:53.089670+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/api/render?output=screenshot&url=https://herooneindex.herokuapp.com/E5/" host=html2png1.herokuapp.com request_id=ee58042b-e3d2-460a-ad05-2d5681f8ab33 fwd="140.XX.XX.XX" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0 protocol=https
2021-06-02T02:19:53.339053+00:00 app[web.1]: 2021-06-02T02:19:53.338Z - error: [render-core.js] Error when rendering page: TimeoutError: Navigation timeout of 30000 ms exceeded
2021-06-02T02:19:53.339252+00:00 app[web.1]: 2021-06-02T02:19:53.339Z - error: [render-core.js] TimeoutError: Navigation timeout of 30000 ms exceeded
2021-06-02T02:19:53.339254+00:00 app[web.1]:     at Promise.then (/app/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21)
2021-06-02T02:19:53.339255+00:00 app[web.1]:   -- ASYNC --
2021-06-02T02:19:53.339255+00:00 app[web.1]:     at Frame.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:111:15)
2021-06-02T02:19:53.339255+00:00 app[web.1]:     at Page.goto (/app/node_modules/puppeteer/lib/Page.js:675:49)
2021-06-02T02:19:53.339256+00:00 app[web.1]:     at Page.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:112:23)
2021-06-02T02:19:53.339256+00:00 app[web.1]:     at Object.render (/app/src/core/render-core.js:128:18)
2021-06-02T02:19:53.339256+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:68:7)
2021-06-02T02:19:53.339335+00:00 app[web.1]: 2021-06-02T02:19:53.339Z - info: [render-core.js] Closing browser..
2021-06-02T02:19:53.354067+00:00 app[web.1]: 2021-06-02T02:19:53.353Z - error: [error-logger.js] Request headers: host=html2png1.herokuapp.com, connection=close, sec-ch-ua=" Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90", sec-ch-ua-mobile=?0, upgrade-insecure-requests=1, user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36, accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9, sec-fetch-site=none, sec-fetch-mode=navigate, sec-fetch-user=?1, sec-fetch-dest=document, accept-encoding=gzip, deflate, br, accept-language=zh-CN,zh;q=0.9, x-request-id=ee58042b-e3d2-460a-ad05-2d5681f8ab33, x-forwarded-for=140.XX.XX.XX, x-forwarded-proto=https, x-forwarded-port=443, via=1.1 vegur, connect-time=0, x-request-start=1622600363087, total-route-time=0
2021-06-02T02:19:53.354150+00:00 app[web.1]: 2021-06-02T02:19:53.354Z - error: [error-logger.js] Request parameters:
2021-06-02T02:19:53.354263+00:00 app[web.1]: 2021-06-02T02:19:53.354Z - error: [error-logger.js] Request body:
2021-06-02T02:19:53.354500+00:00 app[web.1]: 2021-06-02T02:19:53.354Z - error: [error-logger.js] { TimeoutError: Navigation timeout of 30000 ms exceeded
2021-06-02T02:19:53.354502+00:00 app[web.1]:     at Promise.then (/app/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21)
2021-06-02T02:19:53.354503+00:00 app[web.1]:   -- ASYNC --
2021-06-02T02:19:53.354503+00:00 app[web.1]:     at Frame.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:111:15)
2021-06-02T02:19:53.354503+00:00 app[web.1]:     at Page.goto (/app/node_modules/puppeteer/lib/Page.js:675:49)
2021-06-02T02:19:53.354504+00:00 app[web.1]:     at Page.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:112:23)
2021-06-02T02:19:53.354505+00:00 app[web.1]:     at Object.render (/app/src/core/render-core.js:128:18)
2021-06-02T02:19:53.354508+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:68:7) name: 'TimeoutError' } 'TimeoutError: Navigation timeout of 30000 ms exceeded\n    at Promise.then (/app/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21)\n  -- ASYNC --\n    at Frame.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:111:15)\n    at Page.goto (/app/node_modules/puppeteer/lib/Page.js:675:49)\n    at Page.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:112:23)\n    at Object.render (/app/src/core/render-core.js:128:18)\n    at process._tickCallback (internal/process/next_tick.js:68:7)'

what can I do

**Comment by qkqpttgf** [comment]
> You can try to increase memory available

I run it in heroku
